# Generated by Django 6.0.4 on 2026-04-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('RECEPTIONIST', 'Receptionist'), ('NURSE', 'Nurse'), ('DOCTOR', 'Doctor'), ('LAB_TECH', 'Lab Technician'), ('PHARMACIST', 'Pharmacist')], default='RECEPTIONIST', max_length=20),
        ),
    ]
