# Generated by Django 6.0.4 on 2026-04-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='clinic_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reg_number',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
