# Generated by Django 6.0.4 on 2026-04-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_patient_clinic_code_alter_patient_reg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='spo2',
            field=models.IntegerField(blank=True, help_text='Blood oxygen saturation percentage', null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='triage_notes',
            field=models.TextField(blank=True, help_text='Clinical observations during triage'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='status',
            field=models.CharField(choices=[('RECEPTION', 'Awaiting Vitals'), ('TRIAGE', 'Awaiting Consultation'), ('CONSULTATION', 'With Doctor'), ('LAB', 'In Laboratory'), ('PHARMACY', 'Awaiting Medication'), ('CLOSED', 'Completed'), ('EMERGENCY', 'Emergency Case')], default='RECEPTION', max_length=20),
        ),
    ]
