# Generated by Django 6.0.4 on 2026-04-10 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_encounter_spo2_encounter_triage_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='encounter',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='doctor_assigned',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_encounters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Urgent'), (3, 'Emergency')], default=1, help_text='1: Normal, 2: Urgent, 3: Emergency'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='spo2',
            field=models.IntegerField(blank=True, help_text='Blood oxygen saturation %', null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='triage_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='clinic_code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='level',
            field=models.IntegerField(blank=True, help_text='e.g. 100, 200, 300…', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reg_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinic.encounter'),
        ),
    ]
