# Generated by Django 6.0.4 on 2026-04-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_patient_options_encounter_checked_in_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patients/photos/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sif_document',
            field=models.FileField(blank=True, help_text='Student Information Form — PDF or image', null=True, upload_to='patients/sif/'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Urgent'), (3, 'Emergency')], default=1),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='status',
            field=models.CharField(choices=[('RECEPTION', 'Awaiting Vitals'), ('TRIAGE', 'Awaiting Consultation'), ('CONSULTATION', 'With Doctor'), ('LAB', 'In Laboratory'), ('PHARMACY', 'Awaiting Medication'), ('CLOSED', 'Completed'), ('EMERGENCY', 'Emergency')], default='RECEPTION', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DISPENSED', 'Dispensed'), ('OUT_OF_STOCK', 'Out of Stock')], default='PENDING', max_length=20),
        ),
    ]
